version: "3.8"

services: 
  node_server:
    build: 
      context: backend
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    volumes: 
      - ./backend:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_db
    environment:
      - DATABASE_DB=database
      - DATABASE_USER=database_user
      - DATABASE_PASSWORD=database_password
      - DATABASE_HOST=mysql_db
  
  mysql_db:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=database
      - MYSQL_USER=database_user
      - MYSQL_PASSWORD=database_password
      - MYSQL_ROOT_PASSWORD=database_root_password
    volumes:
      - "./mysql/init/database_initialize.sql:/docker-entrypoint-initdb.d/1.sql"
    